### ISSUE TITLE
tasmocompiler stop working on docker

### ISSUE THREAD

**Issue by rt400** [benzino77/tasmocompiler#215]
Hi,
i have the docker and i cant download the source , i got error `Error:Switching to branch development failed`

and the log i see `fatal: 'development' is not a commit and a branch 'development' cannot be created from it

2021-08-02T11:19:33.352Z compile Error: Switching to branch development failed

    at switchToBranch (/tasmocompiler/server/git/git.js:92:13)

    at processTicksAndRejections (internal/process/task_queues.js:97:5)`

Any idea ??

**Comment by benzino77** [comment]
Hi there. It's looks like there is something wrong with local git repository. Please remove your docker container, pull the newest docker image and start Tasmocompiler again:
```bash
docker stop <name_of_tasmocompipler_container>
docker rm <name_of_tasmocompipler_container>
docker pull benzino77/tasmocompiler
docker start <options>
```

**Comment by rt400** [comment]
I fix it with strange way...
I run first ESP8266 compile and then I return and change it to ESP32 and the compile work OK..
any idea ?

**Comment by benzino77** [comment]
This one `Error: Invalid '/tmp/Tasmota/platformio.ini' (project configuration file): 'No section: 'common32''` is really strange. It looks like there is a problem with `platformio.ini` file which is not "touched" by TasmoCompiler. 

`Can not remove temporary directory /tmp/Tasmota/.pio/build` is also strange. It looks like there can be a problem with file permisions on your docker host. Do you have any other place to run TC in docker and check this problems still exists?

**Comment by rt400** [comment]
@benzino77 i just test in other machine with docker and get the same error.

**Comment by benzino77** [comment]
I'm trying to reproduce this situation 
```bash
docker pull benzino77/tasmocompiler # to have the latest v6.0.0 version of tasmocompiler
docker run --rm --name tasmocompiler -p 3000:3000 -e DEBUG=server,git,compile benzino77/tasmocompiler
```
Open my browser, and point it to `http://localhost:3000`. Hit `REFRESH SOURCE` button (to have the latest Tasmota changes) and choose  `ESP32 Generic` board - leave all  preselected features as they are and do not choose any additional. Hit `COMPILE` button. The compilation process is performed without errors and I can download new ESP32 binary firmware.


Could you please provide steps you are doing to let me reproduce your problem?

**Comment by j0n1th4n** [comment]
Hi there,
i installed tasmocompiler yesterday for the first time ever. Great project by the way.
`ESP32 Generic` is working for me as well but when i try `M5Stack Core2` with `Development` version, i get the same error. `v9.5.0` is compiling successfully.

``Can not remove temporary directory `/tmp/Tasmota/.pio/build`. Please remove it manually to avoid build issues
Error: Invalid '/tmp/Tasmota/platformio.ini' (project configuration file): 'No section: 'common32''
Finished. Exit code: 1.
``

**Comment by benzino77** [comment]
I have found that there are many incompatibilities and breaking changes between Tasmota `latest stable` version (9.5.x) and its `development` branch. For now it is impossible to have `stable` and `development` version working at the same time with TasmoCompiler.
As the message stated section `common32` was removed with this [PR](https://github.com/arendst/Tasmota/pull/12442) which makes current TasmoCompiler incompatible with `development` version. My suggestion is to use `stable` version in other case you need to compile Tasmota using other methods.

A while ago I started [discussion](https://github.com/arendst/Tasmota/discussions/12516) on Tasmota github page to point that changes in Tasmota code can be introduced in different/more user friendly way but it not became very popular post ;)

PS.
The same error will arise using TasmoCompiler on gitpod or running from sources.

**Comment by benzino77** [comment]
I think that TasmoCompiler should have two branches: **stable** to compile last stable Tasmota versions, and **development** which will be compatible with Tasmota dev branch. When new Tasmota release is published, **development** branch of TasmoCompiler will become **stable**. Supporting both stable and development versions of Tasmota in TasmoCompiler will not be possible at the same time.

**Comment by probonopd** [comment]
Trying to compile development, running into

```
Can not remove temporary directory `/tmp/Tasmota/.pio/build`. Please remove it manually to avoid build issues
Error: Invalid '/tmp/Tasmota/platformio.ini' (project configuration file): 'No section: 'irremoteesp_full''
Finished. Exit code: 1.
```

**Comment by benzino77** [comment]
As I said: 
> The same error will arise using TasmoCompiler on gitpod or running from sources.

Current TasmoCompiler version is incompatibile with current develeopment branch of Tasmota.

**Comment by benzino77** [comment]
Currently I'm short of time... but  I will eventually add those two boards to TC.

ps.
There is no need for being sorry - you do what you have to do! I'm glad to hear that you consider current `platformio` setup as rock solid.

**Comment by Jason2866** [comment]
@benzino77 new Tasmota release will be on 19.th of October. Only "new" Platformio setup is used than.

**Comment by benzino77** [comment]
I just released new version (v7.0.0) of TasmoCompier which should be fully compatible with  Tasmota version v10.0.0.
