### ISSUE TITLE
cant compile in v10.0.0

### ISSUE THREAD

**Issue by CommunityJoshua** [benzino77/tasmocompiler#320]
i get this error:

Traceback (most recent call last):
  File "/usr/local/bin/pio", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'zeroconf<1' distribution was not found and is required by platformio
Finished. Exit code: 1.

i was running v9.2.2 without any problems. then after upgrade to v10.0.0, compiling in all different settings is not possible. 
my docker instance running and managed on unraid v6.11.5. 

docker run
  -d
  --name='tasmocompiler'
  --net='bridge'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="UnRaidTower"
  -e HOST_CONTAINERNAME="tasmocompiler"
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:3000]'
  -l net.unraid.docker.icon='https://i.imgur.com/r0aWv9M.jpg'
  -p '3000:3000/tcp' 'benzino77/tasmocompiler'
304286b7fc1b33ed3a3118a4fb24d13e385943a1de75f9cb81b642468bafe715

![Screenshot 2023-01-02 221609](https://user-images.githubusercontent.com/21293543/210278560-09a1c065-9e4a-433b-807f-5babf595d9ae.png)
![Screenshot 2023-01-02 221625](https://user-images.githubusercontent.com/21293543/210278561-ebdb96de-f83f-4303-a38b-5125cd871f73.png)
![Screenshot 2023-01-02 221632](https://user-images.githubusercontent.com/21293543/210278562-d0723c49-509e-40df-9e93-c67a3eff7056.png)
![Screenshot 2023-01-02 221634](https://user-images.githubusercontent.com/21293543/210278563-143b634c-7e14-4d6b-8dfa-c883134ae8a3.png)

**Comment by benzino77** [comment]
I released new version v10.0.1 - pull new image and let me know if that fix your problem.

**Comment by CommunityJoshua** [comment]
Yes, compiled successfully
